server {
  listen $PORT;
  server_name npm.ngfk.dev;

  location / {
    proxy_pass https://europe-west4-npm.pkg.dev/ngfk-registry/npm/;

    # Send traffic to the backend
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-for $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $remote_addr;
    proxy_set_header X-Forwarded-Protocol $scheme;

    # Send websocket data to the backend
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
