name: Deployment
on:
  push:
    branches:
      - main
  pull_request:

env:
  GCP_WIP_SA: github-actions@ngfk-registry.iam.gserviceaccount.com
  GCP_WIP: projects/219532496197/locations/global/workloadIdentityPools/github/providers/github-actions
  VERDACCIO_IMAGE: ${{ format('{0}:{1}', 'ngfk-registry/verdaccio', github.sha) }}

jobs:
  docker_verdaccio:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@main
      - name: Authentication gcloud
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ env.GCP_WIP }}"
          service_account: "${{ env.GCP_WIP_SA }}"
      - name: Authenticate docker
        uses: "docker/login-action@v1"
        with:
          registry: "europe-west4-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Build docker image
        run: docker build verdaccio -t $VERDACCIO_IMAGE
      - name: Tag docker image
        run: docker tag $VERDACCIO_IMAGE europe-west4-docker.pkg.dev/$GCP_PROJECT/docker/$VERDACCIO_IMAGE
      - name: Push docker image
        run: docker push europe-west4-docker.pkg.dev/$GCP_PROJECT/docker/$VERDACCIO_IMAGE

  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    needs:
      - docker_verdaccio
    steps:
      - uses: actions/checkout@main
      - name: Authentication gcloud
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ env.GCP_WIP }}"
          service_account: "${{ env.GCP_WIP_SA }}"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: >-
          terraform init
          -backend-config="bucket=$GCP_PROJECT-tf-state"
        working-directory: terraform
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: terraform
      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: terraform
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: >-
          terraform plan
          -no-color
          -input=false
          -var="project_id=$GCP_PROJECT"
        working-directory: terraform
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: >-
          terraform apply
          -auto-approve
          -input=false
          -var="project_id=$GCP_PROJECT"
          -var="verdaccio_image=europe-west4-docker.pkg.dev/$GCP_PROJECT/docker/$VERDACCIO_IMAGE"
        working-directory: terraform
